# PATH: ~/.config/starship.toml

format = "$all"

# Wait 30 milliseconds for starship to check files under the current directory
scan_timeout = 30

# Wait 30 milliseconds for commands (git status for e.g)
command_timeout = 30

[username]
format = "[$user]($style) at "
style_user = "#D7AF87"
disabled = false
show_always = true

[git_status]
ahead = "⇡${count}"
diverged = "⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"

[git_branch]
# trancation_lenght = 10

[directory]
fish_style_pwd_dir_length = 0
truncation_length = 8
truncation_symbol = "…/"
truncate_to_repo = false

[status]
disabled = false
symbol = "X"
pipestatus = true
map_symbol = true
format = '[\[$symbol$common_meaning$signal_name$maybe_int\]]($style) '

[c]
disabled = false

[cmake]
disabled = false

[rust]
disabled = false

[python]
disabled = false
pyenv_version_name = true
# detect_files = []
# detect_extensions = []

